import React from "react";
export const celebrities = [
  {key: "tom", label: "Tom cruise"},
  {key: "rock", label: "The rock"},
  {key: "zendeya", label: "Zendeya"},
  {key: "taylor", label: "Taylor Swift"},
  {key: "hugh", label: "Hugh Jackman"},
  {key: "Drake", label: "Drake"},
  {key: "beast", label: "Mr. Beast"},
  {key: "bigb", label: "Amitabh Bachchan"},
  {key: "modi", label: "Narendra Modi"},
  {key: "sal", label: "Sal Khan"},
  {key: "grant", label: "3Blue1Brown"},
  {key: "joe", label: "Joe Rogan"},
  {key: "muskmelon", label: "Elon musk"}
];

export const learningstyles = [
    {key: "kurz", label: "Kurzgesagt"},
    {key: "peppa", label: "Peppa Pig"},
    {key: "coco", label: "CocoMelon"},
    {key: "sal", label: "KhanAcademy"},
    {key: "grant", label: "3Blue1Brown"},
    {key: "eli5", label: "Explain Like I'm 5"},
  ];

  export const animationStyles = [
    {key: "retro", label: "Retro"},
    {key: "modern", label: "Modern"},
    {key: "cartoon", label: "Cartoon"},
    {key: "anime", label: "Anime"},
    {key: "3d", label: "3D"},
    {key: "black", label: "Black and White"},
    {key: "color", label: "Colorful"},
    {key: "monochrome", label: "Monochrome"},
    {key: "sketch", label: "Sketch"},
    {key: "painting", label: "Painting"},
    {key: "watercolor", label: "Watercolor"},
    {key: "pencil", label: "Pencil"},
    {key: "digital", label: "Digital"},
    {key: "hand", label: "Hand Drawn"},
    {key: "stop", label: "Stop Motion"},
    {key: "motion", label: "Motion Graphics"},
    {key: "clay", label: "Claymation"},
    {key: "sand", label: "Sand Animation"},
    {key: "cut", label: "Cut Out"},
    {key: "pixel", label: "Pixel Art"},
    {key: "vector", label: "Vector Art"},
    {key: "motion", label: "Motion Graphics"},
  ]


export const allLanguagesoftheworld = [
    {key: "en", label: "English"},
    {key: "es", label: "Spanish"},
    {key: "fr", label: "French"},
    {key: "de", label: "German"},
    {key: "it", label: "Italian"},  
    {key: "pt", label: "Portuguese"},
    {key: "ru", label: "Russian"},
    {key: "ja", label: "Japanese"},
    {key: "ko", label: "Korean"},
    {key: "zh", label: "Chinese"},
    {key: "ar", label: "Arabic"},
    {key: "hi", label: "Hindi"},
    {key: "bn", label: "Bengali"},
    {key: "pa", label: "Punjabi"},
    {key: "te", label: "Telugu"},
    {key: "mr", label: "Marathi"},
    {key: "ta", label: "Tamil"},
    {key: "ur", label: "Urdu"},
    {key: "gu", label: "Gujarati"},
    {key: "kn", label: "Kannada"},
    {key: "ml", label: "Malayalam"},
    {key: "or", label: "Oriya"},
    {key: "as", label: "Assamese"},
    {key: "mr", label: "Marathi"},
    {key: "sd", label: "Sindhi"},
    {key: "ps", label: "Pashto"},
    {key: "fa", label: "Persian"},
    {key: "tr", label: "Turkish"},
    {key: "vi", label: "Vietnamese"},
    {key: "th", label: "Thai"},
    {key: "ms", label: "Malay"},
    {key: "fil", label: "Filipino"},
    {key: "id", label: "Indonesian"},
    {key: "sw", label: "Swahili"},


]
